apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: robot-shop
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.16.0.142
    path: /data/mongodb
  persistentVolumeReclaimPolicy: Retain
