apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine3.20
        ports:
        - containerPort: 6379
        livenessProbe:
         tcpSocket:
           port: 6379
         initialDelaySeconds: 15
         periodSeconds: 10
        readinessProbe:
         exec:
           command: ["redis-cli", "ping"]
         initialDelaySeconds: 5
         periodSeconds: 5
