apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Andherson333333/robot-shop.git
    targetRevision: HEAD
    path: Infrastructure-cloud-EKS/infra-node/metrics-server/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
