apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs-pv
  namespace: monitoring
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/prometheus
    server: 172.16.0.142
  claimRef:
    name: prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0
    namespace: monitoring
  storageClassName: ""  

