apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: robot-shop
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/cities?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "shipping"
