apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: catalogue
  namespace: robot-shop
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  service:
    port: 8080
  analysis:
    interval: 30s
    threshold: 5
    maxWeight: 50    # Balance final 50/50
    stepWeight: 10   # Incrementos del 10%
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 500
      interval: 1m
