loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: gp3-default
    nodeSelector:
      node-type: infrastructure
      workload-type: platform
    tolerations:
      - key: "workload-type"
        value: "infrastructure"
        effect: "PreferNoSchedule"

  promtail:
    enabled: true
    tolerations:
      - operator: "Exists"  
    daemonset:
      useHostPid: false
      useHostNetwork: false
    config:
      snippets:
        extraRelabelConfigs:
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: log_type
            action: replace
            regex: istio-proxy
            replacement: envoy
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: log_type
            action: replace
            regex: .+
            replacement: application

  grafana:
    enabled: false
  fluent-bit:
    enabled: false
  filebeat:
    enabled: false
  logstash:
    enabled: false
