apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: robot-shop
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb
  persistentVolumeReclaimPolicy: Retain
