apiVersion: batch/v1
kind: Job
metadata:
  name: robot-shop-load-test-8
  namespace: robot-shop
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: load-tester-web
        image: fortio/fortio:latest
        command: ["/usr/bin/fortio"]
        args: ["load", "-qps=5", "-c=2", "-t=30s", "tcp://web:8080"]
      - name: load-tester-catalogue
        image: fortio/fortio:latest
        command: ["/usr/bin/fortio"]
        args: ["load", "-qps=5", "-c=2", "-t=30s", "tcp://catalogue:8080"]
      - name: load-tester-cart
        image: fortio/fortio:latest
        command: ["/usr/bin/fortio"]
        args: ["load", "-qps=5", "-c=2", "-t=30s", "tcp://cart:8080"]
      - name: load-tester-user
        image: fortio/fortio:latest
        command: ["/usr/bin/fortio"]
        args: ["load", "-qps=5", "-c=2", "-t=30s", "tcp://user:8080"]
      - name: load-tester-shipping
        image: fortio/fortio:latest
        command: ["/usr/bin/fortio"]
        args: ["load", "-qps=5", "-c=2", "-t=30s", "tcp://shipping:8080"]
      - name: load-tester-payment
        image: fortio/fortio:latest
        command: ["/usr/bin/fortio"]
        args: ["load", "-qps=5", "-c=2", "-t=30s", "tcp://payment:8080"]
      restartPolicy: OnFailure
