global:
  nodeSelector:
    node-type: infrastructure
    workload-type: platform
  # Configuración de tolerancias para todos los componentes 
  tolerations:
  - key: "workload-type"
    value: "infrastructure"
    effect: "PreferNoSchedule"

base:
  enabled: true

istiod:
  meshConfig:
    enableTracing: true
    extensionProviders:
      - name: jaeger
        opentelemetry:
          port: 4317
          service: jaeger-collector.istio-system.svc.cluster.local
