apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/cascade-delete: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/Andherson333333/robot-shop.git
    targetRevision: HEAD
    path: Infrastructure-cloud-EKS/infra-node/Kiali
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
