apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: robot-shop-telemetry
  namespace: robot-shop
spec:
  tracing:
    - providers:
        - name: jaeger
      randomSamplingPercentage: 100.0
