meshConfig:
  enableTracing: true
  defaultConfig:
    tracing: {}
  extensionProviders:
    - name: jaeger
      opentelemetry:
        port: 4317
        service: jaeger-collector.istio-system.svc.cluster.local

