# Servicio Headless para MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: robot-shop
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
# Servicio normal para MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: robot-shop
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
