apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: robot-shop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-default
  resources:
    requests:
      storage: 1Gi
