apiVersion: v2
name: prometheus-stack
description: Kube Prometheus Stack Configuration
type: application
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 70.0.2
    repository: https://prometheus-community.github.io/helm-charts
