kube-prometheus-stack:
  # Global configuration for all components
  global:
    nodeSelector:
      node-type: infrastructure
      workload-type: platform
    tolerations:
    - key: "workload-type"
      value: "infrastructure"
      effect: "PreferNoSchedule"
  prometheusOperator:
    enabled: true
    # Configuration for the operator
    nodeSelector:
      node-type: infrastructure
      workload-type: platform
    tolerations:
    - key: "workload-type"
      value: "infrastructure"
      effect: "PreferNoSchedule"
  prometheus:
    enabled: true
    # Configuration for Prometheus
    prometheusSpec:
      retention: "15d"
      # NodeSelector and tolerations configuration for Prometheus
      nodeSelector:
        node-type: infrastructure
        workload-type: platform
      tolerations:
      - key: "workload-type"
        value: "infrastructure"
        effect: "PreferNoSchedule"
      # Selectors to avoid duplicates
      serviceMonitorSelector:
        matchLabels:
          release: prometheus-stack
      podMonitorSelector:
        matchLabels:
          release: prometheus-stack
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3-default
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  grafana:
    enabled: true
    adminPassword: admin
    # Configuration for Grafana
    nodeSelector:
      node-type: infrastructure
      workload-type: platform
    tolerations:
    - key: "workload-type"
      value: "infrastructure"
      effect: "PreferNoSchedule"
    persistence:
      enabled: true
      storageClassName: gp3-default
      size: 10Gi
  alertmanager:
    enabled: true
    # Configuration for AlertManager
    alertmanagerSpec:
      nodeSelector:
        node-type: infrastructure
        workload-type: platform
      tolerations:
      - key: "workload-type"
        value: "infrastructure"
        effect: "PreferNoSchedule"
      retention: 120h
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3-default
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  # Additional configurations for other components
  kubeStateMetrics:
    # Must run on infrastructure nodes
    nodeSelector:
      node-type: infrastructure
      workload-type: platform
    tolerations:
    - key: "workload-type"
      value: "infrastructure"
      effect: "PreferNoSchedule"
  # Node Exporter must run on all nodes to collect metrics
  nodeExporter:
    nodeSelector: {}  
    tolerations:
    - operator: "Exists"  
# Ingress configuration unchanged
ingress:
  prometheus:
    enabled: true
    #className: nginx-external
    className: nginx-internal
    host: dev1-prometheus.andherson33.click
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    service:
      name: prometheus-stack-kube-prom-prometheus
      port: 9090
  grafana:
    enabled: true
    className: nginx-internal
    #className: nginx-external
    host: dev1-grafana.andherson33.click
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    service:
      name: prometheus-stack-grafana
      port: 80
