apiService:
  create: true
args:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --metric-resolution=15s
  - --secure-port=10250
  - --kubelet-insecure-tls
# Configuration to run on infrastructure nodes
nodeSelector:
  node-type: infrastructure
  workload-type: platform
# Tolerations to allow running on nodes with taints
tolerations:
- key: "workload-type"
  value: "infrastructure"
  effect: "PreferNoSchedule"
