flagger:
  meshProvider: "istio"
  metricsServer: "http://prometheus-stack-kube-prom-prometheus.monitoring:9090"
  podMonitor:
    enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"
  logLevel: "info"
  rbac:
    create: true
    pspEnabled: false
  serviceAccount:
    create: true
    name: "flagger"
  metrics:
    enabled: true
  tolerations:
    - key: "workload-type"
      value: "infrastructure"
      effect: "PreferNoSchedule"
  nodeSelector:
    node-type: infrastructure
    workload-type: platform
  affinity: {}
  prometheus:
    install: false
  istio:
    controllerMetricsInterval: "15s"
    controllerIstioTelemetryInterval: "5s"

