apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: monitoring
type: Opaque
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        version: 1
        editable: false
        jsonData:
          maxLines: 1000
          timeout: 30
          minInterval: 1m
          liveEnabled: false
