{{- if .Values.ingress.prometheus.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  {{- with .Values.ingress.prometheus.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.prometheus.className }}
  tls:
  - hosts:
    - {{ .Values.ingress.prometheus.host }}
  rules:
  - host: {{ .Values.ingress.prometheus.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.prometheus.service.name }}
            port:
              number: {{ .Values.ingress.prometheus.service.port }}
{{- end }}  # Faltaba este end para cerrar el if de prometheus
---
{{- if .Values.ingress.grafana.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  {{- with .Values.ingress.grafana.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.grafana.className }}
  tls:
  - hosts:
    - {{ .Values.ingress.grafana.host }}
  rules:
  - host: {{ .Values.ingress.grafana.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.grafana.service.name }}
            port:
              number: {{ .Values.ingress.grafana.service.port }}
{{- end }}
