apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flagger-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Andherson333333/robot-shop.git
    targetRevision: master
    path: Infrastructure-cloud-EKS/infra-node/Flagger-helm/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: flagger-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
