name: Payment Service CI

permissions:
  contents: write
  
on:
  workflow_dispatch:
  push:
    paths:
      - 'payment/**'
      - '.github/workflows/payment-ci.yml'
    branches: [ "main", "master" ]
    
env:
  PRODUCTION_MODE: false
  
jobs:
  cancel-redundant:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  build-and-test:
    needs: cancel-redundant
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        continue-on-error: ${{ env.PRODUCTION_MODE != 'true' }}
        run: |
          cd /home/runner/work/robot-shop/robot-shop/payment
          pip install -r requirements.txt

      - name: Run Tests (if available)
        if: success()
        continue-on-error: ${{ env.PRODUCTION_MODE != 'true' }}
        run: |
          cd /home/runner/work/robot-shop/robot-shop/payment
          if [ -d "tests" ] || [ -f "test_*.py" ]; then
            python -m pytest
          else
            echo "No test files found"
          fi

      - name: Run Security Scan
        continue-on-error: ${{ env.PRODUCTION_MODE != 'true' }}
        run: |
          cd /home/runner/work/robot-shop/robot-shop/payment
          pip install bandit
          bandit -r .

      - name: SonarCloud Scan
        continue-on-error: ${{ env.PRODUCTION_MODE != 'true' }}
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=robot-shop
            -Dsonar.organization=robot-shop
            -Dsonar.sources=payment
            -Dsonar.python.version=3.9
            -Dsonar.c.file.suffixes=-
            -Dsonar.cpp.file.suffixes=-
            -Dsonar.objc.file.suffixes=-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        continue-on-error: ${{ env.PRODUCTION_MODE != 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./payment
          push: true
          tags: andherson1039/rs-payment:${{ github.sha }}

      - name: Update Deployment File
        continue-on-error: ${{ env.PRODUCTION_MODE != 'true' }}
        run: |
          sed -i 's|image: andherson1039/rs-payment:.*|image: andherson1039/rs-payment|g' Infrastructure-onprem/K8s/manifiestos/payment-deployment.yaml
          sed -i "s|image: andherson1039/rs-payment|image: andherson1039/rs-payment:${{ github.sha }}|g" Infrastructure-onprem/K8s/manifiestos/payment-deployment.yaml
          echo "Updated deployment file:"
          cat Infrastructure-onprem/K8s/manifiestos/payment-deployment.yaml

      - name: Commit and Push Changes
        continue-on-error: ${{ env.PRODUCTION_MODE != 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Infrastructure-onprem/K8s/manifiestos/payment-deployment.yaml
          git commit -m "Update payment image to ${{ github.sha }}"
          git push
