apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robot-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Andherson333333/robot-shop.git
    targetRevision: HEAD
    path: Infrastructure-cloud-EKS/infra-aplicacion/K8s/manfiestos
  destination:
    server: https://kubernetes.default.svc
    namespace: robot-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
